# This is a basic workflow to help you get started with Actions

name: Deploy Apigee Proxy

# Controls when the workflow will run
on: [push, pull_request, workflow_dispatch]

env:
  GCP_SA_CREDS: ${{ secrets.GOOGLE_CREDENTIALS }}
  GCP_SA_FILE: ${{ vars.GCP_SA_KEY }}
  GCP_SA: ${{ vars.GCP_SA }}
  GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: 'Use gcloud CLI'
        run: |
          gcloud info
          export GOOGLE_APPLICATION_CREDENTIALS=$(echo $GCP_SA_CREDS)
          echo ${GOOGLE_APPLICATION_CREDENTIALS} > creds.json
          export GOOGLE_APPLICATION_CREDENTIALS=creds.json
          echo This is my Google Project: $GCP_PROJECT_ID
          echo This is my Google Service Account: $GCP_SA
          gcloud config set project $GCP_PROJECT_ID
          gcloud config set account $GCP_SA
          gcloud auth login --cred-file=creds.json
          gcloud auth print-access-token

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
