name: Deploy Apigee Manual

on: [workflow_dispatch]

env:
  GCP_SA_CREDS: ${{ secrets.GOOGLE_CREDENTIALS }}
  GCP_SA: ${{ vars.GCP_SA }}
  GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  PROXY_NAME: ${{ vars.PROXY_NAME }}
  APIGEE_ENV: ${{ vars.APIGEE_ENV }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Setting-up-GCP
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      #Setup GCP
      - name: 'Setup GCP'
        run: |
          apt-get update
          apt-get install -y python3
